name: Build from Containerfile
on:
  push:
  pull_request:
  schedule:
    - cron: "33 3 * * *"

jobs:
  build:
    name: Build busybox
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      IMAGE_NAME: busybox
      REGISTRY: ghcr.io/bengtfredh
    steps:
    - name: Clone the repository
      uses: actions/checkout@v3

    - name: Buildah Action
      id: build-busybox
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./busybox.containerfile

    - name: Buildah Action
      id: build-distroless
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./distroless.containerfile

    - name: Buildah Action
      id: build-httpd
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./httpd.containerfile

    - name: Buildah Action
      id: build-microdnf
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./microdnf.containerfile

    - name: Buildah Action
      id: build-nginx
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./nginx.containerfile

    - name: Buildah Action
      id: build-openssl
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ env.IMAGE_NAME }}
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./busybox.containerfile

    - name: Log in to the GitHub Container registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push to GitHub Container Repository
      id: push-busybox-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-busybox.outputs.image }}
        tags: ${{ steps.build-busybox.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Push to GitHub Container Repository
      id: push-distroless-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-distroless.outputs.image }}
        tags: ${{ steps.build-distroless.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Push to GitHub Container Repository
      id: push-httpd-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-httpd.outputs.image }}
        tags: ${{ steps.build-httpd.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Push to GitHub Container Repository
      id: push-microdnf-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-microdnf.outputs.image }}
        tags: ${{ steps.build-microdnf.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Push to GitHub Container Repository
      id: push-nginx-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-nginx.outputs.image }}
        tags: ${{ steps.build-nginx.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Push to GitHub Container Repository
      id: push-openssl-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-openssl.outputs.image }}
        tags: ${{ steps.build-openssl.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Log in to the Harbor Container registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: cr.fredhs.net
        username: github
        password: ${{ secrets.CR_PASSWORD }}

    - name: Push to Harbor Container Repository
      id: push-busybox-to-harbor
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-busybox.outputs.image }}
        tags: ${{ steps.build-busybox.outputs.tags }}
        registry: cr.fredhs.net/fedora

    - name: Push to GitHub Container Repository
      id: push-distroless-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-distroless.outputs.image }}
        tags: ${{ steps.build-distroless.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Push to GitHub Container Repository
      id: push-httpd-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-httpd.outputs.image }}
        tags: ${{ steps.build-httpd.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Push to GitHub Container Repository
      id: push-microdnf-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-microdnf.outputs.image }}
        tags: ${{ steps.build-microdnf.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Push to GitHub Container Repository
      id: push-nginx-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-nginx.outputs.image }}
        tags: ${{ steps.build-nginx.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Push to GitHub Container Repository
      id: push-openssl-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-openssl.outputs.image }}
        tags: ${{ steps.build-openssl.outputs.tags }}
        registry: ${{ env.REGISTRY }}
