name: Build from Containerfile
on:
  push:
  pull_request:
  schedule:
    - cron: "44 4 * * *"

jobs:
  build:
    name: Build Containerfiles
    runs-on: ubuntu-latest
    permissions:
      packages: write
    env:
      REGISTRY: ghcr.io/bengtfredh
    steps:
    - name: Clone the repository
      uses: actions/checkout@v3

    - name: Buildah Action busybox
      id: build-busybox
      uses: redhat-actions/buildah-build@v2
      with:
        image: busybox
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./busybox.containerfile

    - name: Buildah Action distroless
      id: build-distroless
      uses: redhat-actions/buildah-build@v2
      with:
        image: distroless
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./distroless.containerfile

    - name: Buildah Action httpd
      id: build-httpd
      uses: redhat-actions/buildah-build@v2
      with:
        image: httpd
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./httpd.containerfile

    - name: Buildah Action microdnf
      id: build-microdnf
      uses: redhat-actions/buildah-build@v2
      with:
        image: microdnf
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./microdnf.containerfile

    - name: Buildah Action nginx
      id: build-nginx
      uses: redhat-actions/buildah-build@v2
      with:
        image: nginx
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./nginx.containerfile

    - name: Buildah Action openssl
      id: build-openssl
      uses: redhat-actions/buildah-build@v2
      with:
        image: openssl
        tags: ${{ github.sha }} latest
        containerfiles: |
          ./busybox.containerfile

    - name: Log in to the GitHub Container registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push busybox to GitHub Container Repository
      id: push-busybox-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-busybox.outputs.image }}
        tags: ${{ steps.build-busybox.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Push distroless to GitHub Container Repository
      id: push-distroless-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-distroless.outputs.image }}
        tags: ${{ steps.build-distroless.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Push httpd to GitHub Container Repository
      id: push-httpd-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-httpd.outputs.image }}
        tags: ${{ steps.build-httpd.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Push microdnf to GitHub Container Repository
      id: push-microdnf-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-microdnf.outputs.image }}
        tags: ${{ steps.build-microdnf.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Push nginx to GitHub Container Repository
      id: push-nginx-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-nginx.outputs.image }}
        tags: ${{ steps.build-nginx.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Push openssl to GitHub Container Repository
      id: push-openssl-to-ghcr
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-openssl.outputs.image }}
        tags: ${{ steps.build-openssl.outputs.tags }}
        registry: ${{ env.REGISTRY }}

    - name: Log in to the Harbor Container registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: cr.fredhs.net
        username: github
        password: ${{ secrets.CR_PASSWORD }}

    - name: Push busybox to Harbor Container Repository
      id: push-busybox-to-harbor
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-busybox.outputs.image }}
        tags: ${{ steps.build-busybox.outputs.tags }}
        registry: cr.fredhs.net/fedora

    - name: Push distroless to Harbor Container Repository
      id: push-distroless-to-harbor
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-distroless.outputs.image }}
        tags: ${{ steps.build-distroless.outputs.tags }}
        registry: cr.fredhs.net/fedora

    - name: Push httpd to Harbor Container Repository
      id: push-httpd-to-harbor
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-httpd.outputs.image }}
        tags: ${{ steps.build-httpd.outputs.tags }}
        registry: cr.fredhs.net/fedora

    - name: Push microdnf to Harbor Container Repository
      id: push-microdnf-to-harbor
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-microdnf.outputs.image }}
        tags: ${{ steps.build-microdnf.outputs.tags }}
        registry: cr.fredhs.net/fedora

    - name: Push nginx to Harbor Container Repository
      id: push-nginx-to-harbor
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-nginx.outputs.image }}
        tags: ${{ steps.build-nginx.outputs.tags }}
        registry: cr.fredhs.net/fedora

    - name: Push openssl to Harbor Container Repository
      id: push-openssl-to-harbor
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-openssl.outputs.image }}
        tags: ${{ steps.build-openssl.outputs.tags }}
        registry: cr.fredhs.net/fedora
